services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab1
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net1

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - net1

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      JWT_SECRET: change_me_in_prod
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: lab1
      PGSSL: 'false'
      CORS_ORIGIN: '*'
    ports:
      - "3000:3000"
    networks:
      - net1

volumes:
  pgdata:

networks:
  net1: